ansiblePower/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('dashboard.urls', namespace="dashboard")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^vmware/', include('vmware.urls', namespace="vmware")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^jobtemplates/', include('jobtemplates.urls', namespace="jobtemplates")),
    url(r'^inventories/', include('inventories.urls', namespace="inventories")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vmware/urls.py
__author__ = 'dborysenko'
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.VmListView.as_view(), name='index'),
    url(r'^vcenterlist/$', views.VcenterListView.as_view(), name='vcenterList'),
    url(r'^vmList/$', views.VmListView.as_view(), name='vmList'),
    url(r'^vcentervmlist/$', views.vcenterVmList, name='vcenterVmList'),
    url(r'^vcentertemplatelist/$', views.vcenterTemplateList, name='vcenterTemplateList'),
    url(r'^filelist/$', views.pushFile, name='pushfile'),
    url(r'^cloneform/$', views.cloneView, name='cloneForm'),
    url(r'^clonevm/$', views.cloneVm, name='cloneVM'),
    url(r'^createvm/$', views.createVmView, name='createVmView'),
    url(r'^cloneform/gettemplatesjs', views.getTemplateJs, name='getTemplateJs'),
    url(r'^vmdetail/(?P<pk>\d+)/', views.VmDetail.as_view(), name='vmDetail'),
]

vmware/models.py
from django.db import models

# Create your models here.


class Vcenter(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    host_name = models.CharField(max_length=255)
    user_name = models.CharField(max_length=15)
    user_password = models.CharField(max_length=15)

    def __unicode__(self):
        return self.host_name


class Vm(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    vm_name = models.CharField(max_length=255)
    vm_ip = models.GenericIPAddressField(null=True)
    vm_subnet = models.GenericIPAddressField(null=True)
    vm_gateway = models.GenericIPAddressField(null=True)
    vm_hostname = models.CharField(max_length=255, null=True)
    vcenter = models.ForeignKey(Vcenter)

    def __unicode__(self):
        return self.vm_name

vmware/forms.py
__author__ = 'dborysenko'
from django import forms
import vmvc
from models import Vcenter


class ClonetForm(forms.Form):
    vm_name = forms.CharField(max_length=255)
    vm_ip = forms.GenericIPAddressField(required=False)
    vm_subnet = forms.GenericIPAddressField(required=False)
    vm_gateway = forms.GenericIPAddressField(required=False)
    vm_hostname = forms.CharField(max_length=255, required=False)
    vm_cluster_name = forms.CharField(max_length=255)
    vm_vcenter = forms.ChoiceField(vmvc.get_vcenters())
    template = forms.ChoiceField()


class CreateVmForm(forms.Form):
    vm_name = forms.CharField(max_length=255)
    vm_ip = forms.GenericIPAddressField(required=False)
    vm_subnet = forms.GenericIPAddressField(required=False)
    vm_gateway = forms.GenericIPAddressField(required=False)
    vm_hostname = forms.CharField(max_length=255, required=False)
    vcenters = forms.ChoiceField(vmvc.get_vcenters())

vmware/views.py
from django.shortcuts import render

# Create your views here.
from .models import Vcenter, Vm
from django.views import generic
from pysphere import VIServer
from django.http import HttpResponse, HttpResponseRedirect
import vmvc
from .forms import ClonetForm, CreateVmForm
from django.views.generic.edit import FormView
import github

class VcenterListView(generic.ListView):
    template_name = 'vmware/vcenterList.html'
    model = Vcenter


class VmListView(generic.ListView):
    model = Vm
    template_name = 'vmware/vmList.html'


class VmDetail(generic.DetailView):
    model = Vm
    template_name = 'vmware/vmDetail.html'

    def get_context_data(self, **kwargs):
        context = super(VmDetail, self).get_context_data(**kwargs)
        context['repoList'] = github.getRepos()
        return context


def createVmView(request):
    if request.method == 'POST':
        form = CreateVmForm(request.POST)
        if form.is_valid():
            vcenter = Vcenter.objects.get(pk=form.cleaned_data['vcenters'])
            vm = Vm(vm_name=form.cleaned_data['vm_name'], vcenter=vcenter, vm_ip=form.cleaned_data['vm_ip'],
                    vm_subnet=form.cleaned_data['vm_subnet'], vm_gateway=form.cleaned_data['vm_gateway'],
                    vm_hostname=form.cleaned_data['vm_hostname'])
            vm.save()
            return HttpResponseRedirect('/vmware')
    else:
        form = CreateVmForm()
    return render(request, 'vmware/createVmForm.html', {'form': form})


def cloneView(request):
    if request.method == 'POST':
        form = ClonetForm(request.POST)
        if form.is_valid():
            print "vcenter cleaned data " + form.cleaned_data['vm_vcenter']
            return HttpResponseRedirect('/vmware')
    else:
        form = ClonetForm()
    return render(request, 'vmware/clone.html', {'form': form})


def vcenterTemplateList(request):
    vcenter = Vcenter.objects.get(pk=request.GET['vc_id'])
    template_names = vmvc.get_templates(vcenter)
    return render(request, 'vmware/vmList.html', {"vms": template_names})


def vcenterVmList(request):
    vcenter = Vcenter.objects.get(pk=request.GET['vc_id'])
    vm_list = vmvc.get_vms(vcenter)
    return render(request, 'vmware/vmList.html', {"object_list": vm_list})


def pushFile(request):
    vcenter = Vcenter.objects.get(pk=1)
    vc = vmvc.connect_vcenter(vcenter)
    vm = vc.get_vm_by_name("dborysenko-test-vm")
    vm.login_in_guest("oracle", "qwer1234")
    files = vm.list_files("/users/oracle")
    vc.disconnect()
    return render(request, 'vmware/fileList.html', {"files": files})


def cloneVm(request):
    vcenter = Vcenter.objects.get(pk=1)
    vc = vmvc.connect_vcenter(vcenter)
    template = vc.get_vm_by_name(request.POST['template'])
    cluster_name = request.POST['vm_cluster_name']
    try:
        cluster = [k for k, v in vc.get_clusters().items() if v == cluster_name][0]
        resource_pool = vc.get_resource_pools(from_mor=cluster).items()[0][0]
    except IndexError, e:
        vc.disconnect()
        print "Error: Cannot find cluster - " + cluster_name
        print str(e)
    template.clone(request.POST['vm_name'], sync_run=False, power_on=False, resourcepool=resource_pool)
    vc.disconnect()
    return HttpResponse("<p>Done!<p>")


def getTemplateJs(request):
    if request.method == 'GET':
        templates = []
        vcenter = Vcenter.objects.get(pk=request.GET['vcenter_id'])
        template_list = vmvc.get_templates(vcenter)
        for template in template_list:
            templates.append('<option>' + template + '</option>')
        return HttpResponse(templates)

vmware/templates/vmware/clone.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    {#    <link rel="icon" href="../../favicon.ico">#}

    <title>Theme Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
{#    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">#}
    <!-- Bootstrap theme -->
{#    <link href="../../dist/css/bootstrap-theme.min.css" rel="stylesheet">#}

    <!-- Custom styles for this template -->
{#    <link href="theme.css" rel="stylesheet">#}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
{#    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>#}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

</head>
<script>
$(function() {
	$("#id_vm_vcenter").change(function() {
		$("#id_template").load("gettemplatesjs?vcenter_id=" + $("#id_vm_vcenter").val());
	});
});
</script>
{% load crispy_forms_tags %}
<form action="{% url 'vmware:cloneForm' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
{#    <input type="submit" value="Clone" />#}
    <button class="btn btn-info" type="submit">Clone</button>
</form>
</html>

vmware/templates/vmware/createVmForm.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    {#    <link rel="icon" href="../../favicon.ico">#}

    <title>Theme Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
{#    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">#}
    <!-- Bootstrap theme -->
{#    <link href="../../dist/css/bootstrap-theme.min.css" rel="stylesheet">#}

    <!-- Custom styles for this template -->
{#    <link href="theme.css" rel="stylesheet">#}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
{#    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>#}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body>
{% load crispy_forms_tags %}
<form action="{% url 'vmware:createVmView' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
{#    <input type="submit" value="Clone" />#}
    <button class="btn btn-info" type="submit">Create</button>
</form>
</body>
</html>

vmware/templates/vmware/fileList.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    {#    <link rel="icon" href="../../favicon.ico">#}

    <title>Theme Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
{#    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">#}
    <!-- Bootstrap theme -->
{#    <link href="../../dist/css/bootstrap-theme.min.css" rel="stylesheet">#}

    <!-- Custom styles for this template -->
{#    <link href="theme.css" rel="stylesheet">#}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
{#    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>#}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body role="document">
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>File Name</th>
            </tr>
            </thead>
            <tbody>
            {% for file in files %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ file.path }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</body>
</html>

vmware/templates/vmware/vcenterList.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    {#    <link rel="icon" href="../../favicon.ico">#}

    <title>Theme Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    {#    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">#}
    <!-- Bootstrap theme -->
    {#    <link href="../../dist/css/bootstrap-theme.min.css" rel="stylesheet">#}

    <!-- Custom styles for this template -->
    {#    <link href="theme.css" rel="stylesheet">#}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    {#    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>#}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body role="document">
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Host Name</th>
                <th>Created</th>
                <th>Modified</th>
            </tr>
            </thead>
            <tbody>
            {% for vcenter_host in object_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ vcenter_host.host_name }}</td>
                    <td>{{ vcenter_host.date_created|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ vcenter_host.date_modified|date:"Y-m-d H:i:s" }}</td>
                    <td>
                         <form action="{% url 'vmware:vcenterVmList' %}" method="get">
{#                            {% csrf_token %}#}
                            <input type="hidden" name="vc_id" value="{{ vcenter_host.id }}" />
                            <button type="submit" class="btn btn-info">Show VMs</button>
                        </form>
                    </td>
                    <td>
                         <form action="{% url 'vmware:vcenterTemplateList' %}" method="get">
{#                            {% csrf_token %}#}
                            <input type="hidden" name="vc_id" value="{{ vcenter_host.id }}" />
                            <button type="submit" class="btn btn-info">Show Templates</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <form action="{% url 'vmware:pushfile' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">PushFile</button>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <a href="cloneform" class="btn btn-info">CloneForm</a>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <a href="createvm" class="btn btn-info">CreateVM</a>
    </div>
</div>


</body>
</html>

vmware/templates/vmware/vmDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    {#    <link rel="icon" href="../../favicon.ico">#}

    <title>Theme Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    {#    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">#}
    <!-- Bootstrap theme -->
    {#    <link href="../../dist/css/bootstrap-theme.min.css" rel="stylesheet">#}

    <!-- Custom styles for this template -->
    {#    <link href="theme.css" rel="stylesheet">#}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    {#    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>#}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    {#    <!--[if lt IE 9]>#}
    {#      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>#}
    {#      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>#}
    {#    <![endif]-->#}

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Optional theme -->
    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">#}

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    {#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>#}


</head>
<body>

<div>
    <p>{{ object.vm_hostname }}</p>

    <p>{{ object.vm_name }}</p>
</div>

{% for repo in repoList %}
    <form action="applyrole" method="post">
        {% csrf_token %}
        <input type="hidden" name="repo" value="{{ repo }}"/>
        <button type="submit" class="btn btn-info">{{ repo }}</button>
    </form>
{% endfor %}

</body>
</html>

vmware/templates/vmware/vmList.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    {#    <link rel="icon" href="../../favicon.ico">#}

    <title>Theme Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
{#    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">#}
    <!-- Bootstrap theme -->
{#    <link href="../../dist/css/bootstrap-theme.min.css" rel="stylesheet">#}

    <!-- Custom styles for this template -->
{#    <link href="theme.css" rel="stylesheet">#}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
{#    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>#}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body role="document">
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>VM Name</th>
                <th>VM Hostname</th>
            </tr>
            </thead>
            <tbody>
            {% for vm in object_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'vmware:vmDetail' pk=vm.pk %}">{{ vm.vm_name }}</a></td>
                    <td>{{ vm.vm_hostname }}</td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <form action="{% url 'vmware:pushfile' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">PushFile</button>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <a href="cloneform" class="btn btn-info">CloneForm</a>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <a href="createvm" class="btn btn-info">CreateVM</a>
    </div>
<div class="row">
    <div class="col-md-6">
        <a href="vcenterlist" class="btn btn-info">VcenterList</a>
    </div>
</div>
</body>
</html>