ansiblePower/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('dashboard.urls', namespace="dashboard")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^vmware/', include('vmware.urls', namespace="vmware")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^jobtemplates/', include('jobtemplates.urls', namespace="jobtemplates")),
    url(r'^inventories/', include('inventories.urls', namespace="inventories")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ProjectIndex.as_view(), name='index'),
    url(r'^createproject', views.createProject.as_view(), name='createProject'),
    url(r'^deleteproject/(?P<pk>\d+)/$', views.deleteProject.as_view(), name='deleteProject'),
    url(r'^editroject/(?P<pk>\d+)/$', views.editProject.as_view(), name='editProject'),
]

vmware/urls.py
__author__ = 'dborysenko'
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.VmListView.as_view(), name='index'),
    url(r'^vcenterlist/$', views.VcenterListView.as_view(), name='vcenterList'),
    url(r'^vmList/$', views.VmListView.as_view(), name='vmList'),
    url(r'^vcentervmlist/$', views.vcenterVmList, name='vcenterVmList'),
    url(r'^vcentertemplatelist/$', views.vcenterTemplateList, name='vcenterTemplateList'),
    url(r'^filelist/$', views.pushFile, name='pushfile'),
    url(r'^cloneform/$', views.cloneView, name='cloneForm'),
    url(r'^clonevm/$', views.cloneVm, name='cloneVM'),
    url(r'^createvm/$', views.createVmView, name='createVmView'),
    url(r'^cloneform/gettemplatesjs', views.getTemplateJs, name='getTemplateJs'),
    url(r'^vmdetail/(?P<pk>\d+)/', views.VmDetail.as_view(), name='vmDetail'),
]

jobtemplates/models.py
from django.db import models
from django.core.exceptions import ValidationError
from projects.models import Projects
from inventories.models import Inventories
import yaml
from yaml.error import MarkedYAMLError
import os


class JobTemplates(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    run_type_choices = (
        ('run', 'Run'),
        ('check', 'Check'),
        ('scan', 'Scan'),
    )
    run_types = models.CharField(max_length=5,
                                 choices=run_type_choices,
                                 default='run')
    project = models.ForeignKey(Projects, null=True, on_delete=models.SET_NULL)
    inventory = models.ForeignKey(Inventories, null=True, on_delete=models.SET_NULL)
    playbook = models.CharField(max_length=255, null=True)
    extra_variables = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return self.name


def validateFolder(value):
    proj = Projects.objects.get(pk=value.pk)
    if os.path.isdir(proj.directory) and os.access(proj.directory, os.W_OK):
        return True
    else:
        raise ValidationError('%s project\'s directory %s not accessible' % (value, proj.directory))


def validateYAML(yamlText):
    try:
        yaml.load(yamlText)
        return True
    except MarkedYAMLError, e:
        raise ValidationError('YAML syntax error: %s' % str(e))


def playbookchoices(directory):
    result = [('', '-----'), ]
    try:
        files = os.listdir(directory)
        for filename in files:
            if filename[-3:] == 'yml':
                result.append((filename, filename))
    except OSError, e:
        pass
    return result

projects/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.db.models import ProtectedError
import os


class Projects(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    directory = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

    # def delete(self, using=None):
    #     try:
    #         self.delete(using=None)
    #     except ProtectedError, e:
    #         raise Exception('Hello World from models')


def validateFolder(value):
    if os.path.isdir(value) and os.access(value, os.W_OK):
        pass
    else:
        raise ValidationError('%s does not exist or not accessible' % value)

projects/forms.py
from django import forms
from .models import Projects, validateFolder


class CreateProjectForm(forms.ModelForm):
    name = forms.CharField(max_length=255)
    description = forms.CharField(max_length=255, required=False)
    directory = forms.CharField(max_length=255, validators=[validateFolder])

    class Meta:
        model = Projects
        exclude = ['date_created', 'date_modified', ]

projects/views.py
from django.views import generic
from django.http import JsonResponse
from .models import Projects
from .forms import CreateProjectForm

# Create your views here.


class ProjectIndex(generic.ListView):
    model = Projects
    template_name = 'projects/projectsIndex.html'
    paginate_by = 5


class createProject(generic.CreateView):
    form_class = CreateProjectForm
    template_name = 'projects/createProject.html'
    success_url = '/projects'


class editProject(generic.UpdateView):
    form_class = CreateProjectForm
    template_name = 'projects/editProject.html'
    model = Projects
    success_url = '/projects'


class deleteProject(generic.DeleteView):
    model = Projects
    success_url = '/projects'
    template_name = 'projects/deleteProject.html'

    def post(self, request, *args, **kwargs):
        self.delete(request, *args, **kwargs)
        return JsonResponse({})

projects/templates/projects/base.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}

projects/templates/projects/createProject.html
{% extends "projects/base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block jumbotron %}
    <div class="col col-md-6">
        <form action="{% url 'projects:createProject' %}" method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    {% bootstrap_icon "ok" %} Create
                </button>
                <a href="{% url 'projects:index' %}" type="button" class="btn btn-default">
                    {% bootstrap_icon "remove" %} Cancel
                </a>
            {% endbuttons %}
        </form>
    </div>
{% endblock jumbotron %}

projects/templates/projects/deleteProject.html
{% extends 'projects/base.html' %}
{% block jumbotron %}
    <div>
    <p>Delete Project {{ object.name }} </p>
    <p>Something goes wrong</p>
    </div>
{% endblock jumbotron %}

projects/templates/projects/editProject.html
{% extends "projects/base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block jumbotron %}
    <div class="col col-md-6">
        <form action="{% url 'projects:editProject' pk=object.pk %}" method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    {% bootstrap_icon "ok" %} Save
                </button>
                <a href="{% url 'projects:index' %}" type="button" class="btn btn-default">
                    {% bootstrap_icon "remove" %} Cancel
                </a>
            {% endbuttons %}
        </form>
    </div>
{% endblock jumbotron %}

projects/templates/projects/modalConfirm.html
<div class="modal fade bs-example-modal-sm" id="deleteconfirmmodal" tabindex="-1" role="dialog"
     aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <h4 class="modal-title" id="mySmallModalLabel">Confirm delete</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button class="btn btn-danger btn-ok">Drop</button>
            </div>
        </div>
    </div>
</div>

projects/templates/projects/pagination.html
    {% if is_paginated %}
        <ul class="pagination pagination-centered">
            {% if page_obj.has_previous %}
{#                <li><a href="?page=1">&laquo;</a></li>#}
                <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
            {% endif %}

            {% for i in paginator.page_range %}
                <li {% if page_obj.number == i %} class="active" {% endif %}><a href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
{#                <li><a href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a></li>#}
            {% endif %}
        </ul>
    {% endif %}

projects/templates/projects/projectsIndex.html
{% extends "projects/base.html" %}
{% block jumbotron %}
    <div>
        <div class="col-md1 col-md-offset-11" align="right">
            <a href={% url 'projects:createProject' %} type="button" class="btn btn-info">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add
            </a>
        </div>
        <div>
            <div class="bs-example" data-example-id="hoverable-table">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Directory</th>
                        <th>Modified</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                        <tr id="row{{ object.pk }}" class="collapse in">
                            <th scope="row">{{ page_obj.start_index|add:forloop.counter|add:"-1" }}</th>
                            <td><a href="{% url 'projects:editProject' object.pk %}">{{ object.name }}</a></td>
                            <td>{{ object.directory }}</td>
                            <td>{{ object.date_modified|date:"Y-m-d H:i:s" }}</td>
                            <td>
                                <button id="deletebutton{{ object.pk }}" type="button" class="btn btn-default btn-xs"
                                        data-target=".bs-example-modal-sm" data-pk="{{ object.pk }}"
                                        data-name="{{ object.name }}"
{#                                        data-posttarget="/projects/deleteproject/">#}
                                        data-posttarget="{% url 'projects:deleteProject' pk=object.pk %}">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                </button>
                                <a href="{% url 'projects:editProject' pk=object.pk %}" class="btn btn-default btn-xs">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
{#                        {{ object.jobtemplates_set.all }}#}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% include 'projects/pagination.html' %}
    {% include 'projects/modalConfirm.html' %}
{% endblock jumbotron %}