ansiblePower/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('dashboard.urls', namespace="dashboard")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^vmware/', include('vmware.urls', namespace="vmware")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^jobtemplates/', include('jobtemplates.urls', namespace="jobtemplates")),
    url(r'^inventories/', include('inventories.urls', namespace="inventories")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from . import views
from django.conf.urls import url


urlpatterns = [
    url(r'^$', views.DashboardView.as_view(), name='index'),
]

inventories/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.InventoriesIndex.as_view(), name='index'),
    url(r'^createinventory/$', views.createInventory.as_view(), name='createInventory'),
    url(r'^editinventory/(?P<pk>\d+)/$', views.editInventory.as_view(), name='editInventory'),
    url(r'^deleteinventory/(?P<pk>\d+)/$', views.deleteInventory.as_view(), name='deleteInventory'),
    url(r'^manageinventory/(?P<pk>\d+)/$', views.manageInventory.as_view(), name='manageInventory'),
    url(r'^createhost/$', views.createHost.as_view(), name='createHost'),
    url(r'^createhost/(?P<inv_id>\d+)/$', views.createHost.as_view(), name='createHost'),
    url(r'^edithost/(?P<pk>\d+)/$', views.editHost.as_view(), name='editHost'),
    url(r'^edithost/(?P<pk>\d+)/(?P<inv_id>\d+)/$', views.editHost.as_view(), name='editHost'),
    url(r'^groupindex/$', views.groupIndex.as_view(), name='groupIndex'),
    url(r'^hostindex/$', views.hostIndex.as_view(), name='hostIndex'),
    url(r'^credentialindex/$', views.credentialIndex.as_view(), name='credentialIndex'),
    url(r'^createcredential/$', views.createCredential.as_view(), name='createCredential'),
    url(r'^editcredential/(?P<pk>\d+)/$', views.editCredential.as_view(), name='editCredential'),
    url(r'^creategroup/$', views.createGroup.as_view(), name='createGroup'),
    url(r'^creategroup/(?P<inv_id>\d+)/$', views.createGroup.as_view(), name='createGroup'),
    url(r'^editgroup/(?P<pk>\d+)/$', views.editGroup.as_view(), name='editGroup'),
    url(r'^editgroup/(?P<pk>\d+)/(?P<inv_id>\d+)/$', views.editGroup.as_view(), name='editGroup'),
    url(r'^managegroup/(?P<pk>\d+)/$', views.manageGroup.as_view(), name='manageGroup'),
    url(r'^managegroup/(?P<pk>\d+)/(?P<inv_id>\d+)/$', views.manageGroup.as_view(), name='manageGroup'),
    url(r'^deletecredential/(?P<pk>\d+)/$', views.deleteCredential.as_view(), name='deleteCredential'),
    url(r'^deletegroup/(?P<pk>\d+)/$', views.deleteGroup.as_view(), name='deleteGroup'),
    url(r'^deletegroup/(?P<pk>\d+)/(?P<inv_id>\d+)/$', views.deleteGroup.as_view(), name='deleteGroup'),
    url(r'^deletehost/(?P<pk>\d+)/$', views.deleteHost.as_view(), name='deleteHost'),
    url(r'^deletehost/(?P<pk>\d+)/(?P<inv_id>\d+)/$', views.deleteHost.as_view(), name='deleteHost'),
    url(r'^showpubkey/(?P<pk>\d+)/$', views.showPubKey, name='showPubKey'),
]

vmware/urls.py
__author__ = 'dborysenko'
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.VmListView.as_view(), name='index'),
    url(r'^vcenterlist/$', views.VcenterListView.as_view(), name='vcenterList'),
    url(r'^vmList/$', views.VmListView.as_view(), name='vmList'),
    url(r'^vcentervmlist/$', views.vcenterVmList, name='vcenterVmList'),
    url(r'^vcentertemplatelist/$', views.vcenterTemplateList, name='vcenterTemplateList'),
    url(r'^filelist/$', views.pushFile, name='pushfile'),
    url(r'^cloneform/$', views.cloneView, name='cloneForm'),
    url(r'^clonevm/$', views.cloneVm, name='cloneVM'),
    url(r'^createvm/$', views.createVmView, name='createVmView'),
    url(r'^cloneform/gettemplatesjs', views.getTemplateJs, name='getTemplateJs'),
    url(r'^vmdetail/(?P<pk>\d+)/', views.VmDetail.as_view(), name='vmDetail'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.


class DashboardView(generic.TemplateView):
    template_name = 'dashboard/index.html'

dashboard/templates/dashboard/base.html
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    {#    <link rel="icon" href="../../favicon.ico">#}

    <title>Navbar Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    {#    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">#}
    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">#}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/navbar.css' %}" rel="stylesheet">
</head>

<body data-feedly-mini="yes">

<div class="container">

    <!-- Static navbar -->
    {% block navbar %}
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href={% url 'dashboard:index' %}>AnsiblePower</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav" id="navbarid">
                        {% block activetab %}
                            <li id="home"><a href={% url 'dashboard:index' %}>Home</a></li>
                            <li id="projects"><a href={% url 'projects:index' %}>Projects</a></li>
{#                            <li id="inventories"><a href={% url 'inventories:index' %}>Inventories</a></li>#}
                            <li id="jobtemplates"><a href="{% url 'jobtemplates:index' %}">JobTemplates</a></li>
                            <li id="contact"><a href="#">Contact</a></li>
                        {% endblock activetab %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Inventory <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href={% url 'inventories:index' %}>Inventory</a></li>
                                <li><a href={% url 'inventories:groupIndex' %}>Groups</a></li>
                                <li><a href="{% url 'inventories:hostIndex' %}">Hosts</a></li>
                                <li><a href="{% url 'inventories:credentialIndex' %}">Credentials</a></li>
                                <li role="separator" class="divider"></li>
                                <li class="dropdown-header">Nav header</li>
                                <li><a href="#">Separated link</a></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="./">Default <span class="sr-only">(current)</span></a></li>
                        <li><a href="../navbar-static-top/">Static top</a></li>
                        <li><a href="../navbar-fixed-top/">Fixed top</a></li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
            <!--/.container-fluid -->
        </nav>
    {% endblock navbar %}
    {% block breadcrumbs %}
        {% clear_breadcrumbs %}
        {% breadcrumb "Home" 'dashboard:index' %}
    {% endblock breadcrumbs %}

    {% block jumbotron %}
        {% render_breadcrumbs %}
    {% endblock jumbotron %}


</div>
<!-- /container -->

{% block jsload %}
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/projects.js' %}"></script>
    <script src="{% static 'js/ansiblePower.js' %}"></script>
{% endblock jsload %}
</body>
</html>

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% block jumbotron %}
        {{ block.super }}
        <div class="jumbotron">
            <h1>AnsiblePower</h1>

            <p>This is project to orchestrate ansible through web console</p>

            <p>
                <a class="btn btn-lg btn-primary" href="https://github.com/AnsiblePower/AnsiblePower" role="button">View
                    source on GitHub »</a>
            </p>
        </div>
    {% endblock jumbotron %}