ansiblePower/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('dashboard.urls', namespace="dashboard")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^vmware/', include('vmware.urls', namespace="vmware")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^jobtemplates/', include('jobtemplates.urls', namespace="jobtemplates")),
    url(r'^inventories/', include('inventories.urls', namespace="inventories")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

inventories/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.InventoriesIndex.as_view(), name='index'),
    url(r'^createinventory/$', views.createInventory.as_view(), name='createInventory'),
    url(r'^editinventory/(?P<pk>\d+)/$', views.editInventory.as_view(), name='editInventory'),
    url(r'^deleteinventory/(?P<pk>\d+)/$', views.deleteInventory.as_view(), name='deleteInventory'),
    url(r'^manageinventory/(?P<pk>\d+)/$', views.manageInventory.as_view(), name='manageInventory'),
    url(r'^createhost/$', views.createHost.as_view(), name='createHost'),
    url(r'^createhost/(?P<inv_id>\d+)/$', views.createHost.as_view(), name='createHost'),
    url(r'^edithost/(?P<pk>\d+)/$', views.editHost.as_view(), name='editHost'),
    url(r'^edithost/(?P<pk>\d+)/(?P<inv_id>\d+)/$', views.editHost.as_view(), name='editHost'),
    url(r'^groupindex/$', views.groupIndex.as_view(), name='groupIndex'),
    url(r'^hostindex/$', views.hostIndex.as_view(), name='hostIndex'),
    url(r'^credentialindex/$', views.credentialIndex.as_view(), name='credentialIndex'),
    url(r'^createcredential/$', views.createCredential.as_view(), name='createCredential'),
    url(r'^editcredential/(?P<pk>\d+)/$', views.editCredential.as_view(), name='editCredential'),
    url(r'^creategroup/$', views.createGroup.as_view(), name='createGroup'),
    url(r'^creategroup/(?P<inv_id>\d+)/$', views.createGroup.as_view(), name='createGroup'),
    url(r'^editgroup/(?P<pk>\d+)/$', views.editGroup.as_view(), name='editGroup'),
    url(r'^editgroup/(?P<pk>\d+)/(?P<inv_id>\d+)/$', views.editGroup.as_view(), name='editGroup'),
    url(r'^managegroup/(?P<pk>\d+)/$', views.manageGroup.as_view(), name='manageGroup'),
    url(r'^managegroup/(?P<pk>\d+)/(?P<inv_id>\d+)/$', views.manageGroup.as_view(), name='manageGroup'),
    url(r'^deletecredential/(?P<pk>\d+)/$', views.deleteCredential.as_view(), name='deleteCredential'),
    url(r'^deletegroup/(?P<pk>\d+)/$', views.deleteGroup.as_view(), name='deleteGroup'),
    url(r'^deletegroup/(?P<pk>\d+)/(?P<inv_id>\d+)/$', views.deleteGroup.as_view(), name='deleteGroup'),
    url(r'^deletehost/(?P<pk>\d+)/$', views.deleteHost.as_view(), name='deleteHost'),
    url(r'^deletehost/(?P<pk>\d+)/(?P<inv_id>\d+)/$', views.deleteHost.as_view(), name='deleteHost'),
    url(r'^showpubkey/(?P<pk>\d+)/$', views.showPubKey, name='showPubKey'),
]

jobtemplates/urls.py
from . import views
from django.conf.urls import url


urlpatterns = [
    url(r'^$', views.JobTemplatesIndex.as_view(), name='index'),
    url(r'^createjobtemplate', views.createJobTemplate.as_view(), name='createJobTemplate'),
    url(r'^editjobtemplate/(?P<pk>\d+)', views.editJobTemplate.as_view(), name='editJobTemplate'),
    url(r'^deletejobtemplate/(?P<pk>\d+)', views.deleteJobTemplate.as_view(), name='deleteJobTemplate'),
    url(r'^runjobtemplate/(?P<pk>\d+)', views.runInv, name='runJobTemplate'),
    url(r'^getjsondirectory/(?P<pk>\d+)', views.getJSONDirectory, name='getJSONDirectory'),
]

vmware/urls.py
__author__ = 'dborysenko'
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.VmListView.as_view(), name='index'),
    url(r'^vcenterlist/$', views.VcenterListView.as_view(), name='vcenterList'),
    url(r'^vmList/$', views.VmListView.as_view(), name='vmList'),
    url(r'^vcentervmlist/$', views.vcenterVmList, name='vcenterVmList'),
    url(r'^vcentertemplatelist/$', views.vcenterTemplateList, name='vcenterTemplateList'),
    url(r'^filelist/$', views.pushFile, name='pushfile'),
    url(r'^cloneform/$', views.cloneView, name='cloneForm'),
    url(r'^clonevm/$', views.cloneVm, name='cloneVM'),
    url(r'^createvm/$', views.createVmView, name='createVmView'),
    url(r'^cloneform/gettemplatesjs', views.getTemplateJs, name='getTemplateJs'),
    url(r'^vmdetail/(?P<pk>\d+)/', views.VmDetail.as_view(), name='vmDetail'),
]

inventories/models.py
from django.db import models
from encrypted_fields import EncryptedCharField, EncryptedTextField


class Inventories(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    variables = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return self.name


class Groups(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    variables = models.TextField(null=True, blank=True)
    inventory = models.ManyToManyField(Inventories)

    def __unicode__(self):
        return self.name


class Hosts(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    ipAddress = models.GenericIPAddressField(null=True)
    port = models.PositiveIntegerField(null=True)
    description = models.CharField(max_length=255, null=True)
    variables = models.TextField(null=True, blank=True)
    hostKey = models.TextField(null=True)
    inventory = models.ManyToManyField(Inventories)
    group = models.ManyToManyField(Groups)
    credentials = models.ForeignKey('Credentials', null=True, on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.name


class Credentials(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True)
    keyOrPassword = models.BooleanField()
    privateKey = EncryptedTextField(null=True)
    publicKey = models.TextField(null=True)
    username = models.CharField(max_length=255, null=True)
    password = EncryptedCharField(max_length=255, null=True)

    def __unicode__(self):
        return self.name

inventories/views.py
from django.views import generic
from django.views.generic.edit import CreateView
from django.http import JsonResponse, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.messages.views import SuccessMessageMixin, messages
from .models import Inventories, Hosts, Groups, Credentials
from .forms import CreateInventoryForm, CreateHostForm, CreateGroupForm, CreateCredentialForm
from Crypto.PublicKey import RSA
import paramiko
import socket


class InventoriesIndex(generic.ListView):
    model = Inventories
    template_name = 'inventories/inventoriesIndex.html'
    paginate_by = 5


class createInventory(generic.CreateView):
    form_class = CreateInventoryForm
    template_name = 'inventories/createInventory.html'
    success_url = '/inventories'


class editInventory(generic.UpdateView):
    form_class = CreateInventoryForm
    model = Inventories
    template_name = 'inventories/editInventory.html'
    success_url = '/inventories'


class manageInventory(generic.UpdateView):
    model = Inventories
    template_name = 'inventories/manageInventory.html'
    form_class = CreateInventoryForm

    def get_context_data(self, **kwargs):
        context = super(manageInventory, self).get_context_data(**kwargs)
        inv_pk = context['object'].pk
        context['hosts_list'] = Hosts.objects.filter(inventory=inv_pk)
        context['all_hosts'] = Hosts.objects.exclude(inventory=inv_pk)
        context['group_list'] = Groups.objects.filter(inventory=inv_pk)
        context['all_groups'] = Groups.objects.exclude(inventory=inv_pk)
        return context

    def get_success_url(self):
        return reverse('inventories:index')


class groupIndex(generic.ListView):
    model = Groups
    template_name = 'inventories/groupIndex.html'
    paginate_by = 10


class manageGroup(generic.UpdateView):
    model = Groups
    template_name = 'inventories/manageGroup.html'
    form_class = CreateGroupForm

    def get_context_data(self, **kwargs):
        context = super(manageGroup, self).get_context_data(**kwargs)
        context['hosts_list'] = Hosts.objects.filter(group=context['object'].pk)
        context['all_hosts'] = Hosts.objects.exclude(group=context['object'].pk)
        if 'inv_id' in self.kwargs:
            context['inv'] = Inventories.objects.get(pk=self.kwargs['inv_id'])
        return context

    def get_success_url(self):
        if 'inv_id' in self.kwargs:
            return reverse('inventories:manageInventory', kwargs={'pk': self.kwargs['inv_id']})
        else:
            return reverse('inventories:groupIndex')


class editGroup(manageGroup):
    model = Groups
    form_class = CreateGroupForm
    template_name = 'inventories/editGroup.html'


class createGroup(SuccessMessageMixin, CreateView):
    form_class = CreateGroupForm
    model = Groups
    template_name = 'inventories/createGroup.html'
    success_message = """Group <a href="{link}" class="alert-link">{groupname}</a> was added successfully
    """

    def get_success_message(self, cleaned_data):
        return self.success_message.format(
            cleaned_data,
            groupname=self.object.name,
            link=reverse('inventories:editGroup', kwargs={'pk': self.object.pk})
        )

    def form_valid(self, form):
        formValid = super(createGroup, self).form_valid(form)
        print self.object.pk
        # TODO: implement same logic in addhost
        messages.add_message(self.request, messages.ERROR, "TESTING!!!")
        return formValid

    def get_context_data(self, **kwargs):
        context = super(createGroup, self).get_context_data(**kwargs)
        if 'inv_id' in self.kwargs:
            context['inv'] = Inventories.objects.get(pk=self.kwargs['inv_id'])
        return context

    def get_form_kwargs(self):
        kwargs = super(createGroup, self).get_form_kwargs()
        if 'inv_id' in self.kwargs:
            kwargs['inv_id'] = self.kwargs['inv_id']
        return kwargs

    def get_success_url(self):
        if 'inv_id' in self.kwargs:
            return reverse('inventories:manageInventory', kwargs={'pk': self.kwargs['inv_id']})
        else:
            return reverse('inventories:groupIndex')


class deleteGroup(generic.DeleteView):
    model = Groups
    template_name = 'inventories/deleteEntity.html'
    success_url = '/inventories'

    def post(self, request, *args, **kwargs):
        if 'inv_id' in self.kwargs:
            print "Untarget group from inventory"
        else:
            print "Delete group"
        self.delete(request, *args, **kwargs)
        return JsonResponse({})


class hostIndex(generic.ListView):
    model = Hosts
    template_name = 'inventories/hostIndex.html'
    paginate_by = 10


class editHost(generic.UpdateView):
    model = Hosts
    form_class = CreateHostForm
    template_name = 'inventories/editHost.html'

    def get_success_url(self):
        if 'inv_id' in self.kwargs:
            return reverse('inventories:manageInventory', kwargs={'pk': self.kwargs['inv_id']})
        else:
            return reverse('inventories:hostIndex')

    def get_form_kwargs(self):
        kwargs = super(editHost, self).get_form_kwargs()
        if 'inv_id' in self.kwargs:
            kwargs['inv_id'] = self.kwargs['inv_id']
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(editHost, self).get_context_data(**kwargs)
        # context['inv_pk'] = Hosts.objects.get(pk=self.kwargs['pk']).inventory.
        # context['inv_pk'] = Inventories.objects.filter(hosts__pk=self.kwargs['pk'])
        if 'inv_id' in self.kwargs:
            context['inv'] = Inventories.objects.get(pk=self.kwargs['inv_id'])
        return context


class createHost(generic.CreateView):
    form_class = CreateHostForm
    model = Hosts
    template_name = 'inventories/createHost.html'

    # Adding to context (templates)
    def get_context_data(self, **kwargs):
        context = super(createHost, self).get_context_data(**kwargs)
        # context['inv_pk'] = self.kwargs['pk']
        if 'inv_id' in self.kwargs:
            context['inv'] = Inventories.objects.get(pk=self.kwargs['inv_id'])
        return context

    def get_success_url(self):
        if 'inv_id' in self.kwargs:
            return reverse('inventories:manageInventory', kwargs={'pk': self.kwargs['inv_id']})
        else:
            return reverse('inventories:hostIndex')

    # Adding to form class instantiating
    def get_form_kwargs(self):
        kwargs = super(createHost, self).get_form_kwargs()
        if 'inv_id' in self.kwargs:
            kwargs['inv_id'] = self.kwargs['inv_id']
        return kwargs

    def form_valid(self, form):
        formValid = super(createHost, self).form_valid(form)
        print "FormVALID"
        # If object was persisted to DB
        if self.object.pk:
            mySocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            if self.object.port:
                port = self.object.port
            else:
                port = 22
            if self.object.ipAddress:
                address = self.object.ipAddress
            else:
                address = self.object.name
            try:
                mySocket.connect((address, port))
                mySocket.close()
            except socket.error, e:
                msg = """WARRNING: host
                <a href={pk} class="alert-link">{hostname}:{port}</a>
                was added, but we can't connect to it\n
                The error was: {error}""".format(
                    hostname=address,
                    port=port,
                    error=str(e),
                    pk=self.object.pk,
                )
                messages.add_message(self.request, messages.ERROR, msg)
        # messages.add_message(self.request, messages.SUCCESS, "TESTING!!!")
        return formValid

    # def form_valid(self, form):
    #     mySocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    #     if form.cleaned_data['port']:
    #         port = form.cleaned_data['port']
    #     else:
    #         port = 22
    #     if form.cleaned_data['ipAddress']:
    #         address = form.cleaned_data['ipAddress']
    #     else:
    #         address = form.cleaned_data['name']
    #     try:
    #         # known_hosts
    #         mySocket.connect((address, port))
    #         myTransport = paramiko.Transport(mySocket)
    #         myTransport.start_client()
    #         sshKey = myTransport.get_remote_server_key()
    #         myTransport.close()
    #         mySocket.close()
    #
    #         # SSH key pairs
    #         new_key = RSA.generate(2048)
    #         form.instance.publicKey = new_key.publickey().exportKey(format='OpenSSH')
    #         form.instance.privateKey = new_key.exportKey()
    #         form.instance.hostKey = sshKey.get_base64()
    #
    #         # Push public key to server
    #         ssh = paramiko.SSHClient()
    #         ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    #         ssh.connect(address, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
    #         cmd = 'echo %s >> $HOME/.ssh/authorized_keys' % new_key.publickey().exportKey(format='OpenSSH')
    #         ssh.exec_command(cmd)
    #         ssh.close()
    #
    #     except socket.error, e:
    #         print str(e)
    #
    #     return super(createHost, self).form_valid(form)


class createCredential(generic.CreateView):
    model = Credentials
    template_name = 'inventories/createCredential.html'
    form_class = CreateCredentialForm

    def get_success_url(self):
        return reverse('inventories:credentialIndex')


class editCredential(generic.UpdateView):
    model = Credentials
    template_name = 'inventories/editCredential.html'
    form_class = CreateCredentialForm

    def get_success_url(self):
        return reverse('inventories:credentialIndex')


class credentialIndex(generic.ListView):

inventories/templates/inventories/base.html
{% extends 'dashboard/base.html' %}

inventories/templates/inventories/credentialIndex.html
{% extends "inventories/base.html" %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Credentials" 'inventories:credentialIndex' %}
{% endblock breadcrumbs %}
{% block jumbotron %}
    {{ block.super }}
    <div id="group-index-data">
        <div class="col-md1 col-md-offset-11" align="right">
            <a href={% url 'inventories:createCredential' %} type="button" class="btn btn-info">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add
            </a>
        </div>
        <div>
            <div class="bs-example" data-example-id="hoverable-table">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Modified</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                        <tr id="row{{ object.pk }}" class="collapse in">
                            <th scope="row">{{ page_obj.start_index|add:forloop.counter|add:"-1" }}</th>
                            <td><a href="{% url 'inventories:editCredential' object.pk %}">{{ object.name }}</a></td>
                            <td>{{ object.date_modified|date:"Y-m-d H:i:s" }}</td>
                            <td>
                                <button id="deletebutton{{ object.pk }}" type="button"
                                        class="btn btn-default btn-xs"
                                        data-target=".bs-example-modal-sm" data-pk="{{ object.pk }}"
                                        data-name="{{ object.name }}"
                                        data-posttarget="/inventories/deletecredential/">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                </button>
                                <a href="{% url 'inventories:editCredential' object.pk %}" class="btn btn-default btn-xs">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% include 'projects/pagination.html' %}
    {% include 'projects/modalConfirm.html' %}
{% endblock jumbotron %}

inventories/templates/inventories/groupIndex.html
{% extends "inventories/base.html" %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Groups" 'inventories:groupIndex' %}
{% endblock breadcrumbs %}
{% block jumbotron %}
    {{ block.super }}
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    {{ message|safe }}
                </div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                {{ message|safe }}
            </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <div id="group-index-data">
        <div class="col-md1 col-md-offset-11" align="right">
            <a href={% url 'inventories:createGroup' %} type="button" class="btn btn-info">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add
            </a>
        </div>
        <div>
            <div class="bs-example" data-example-id="hoverable-table">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Modified</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                        <tr id="row{{ object.pk }}" class="collapse in">
                            <th scope="row">{{ page_obj.start_index|add:forloop.counter|add:"-1" }}</th>
                            <td><a href="{% url 'inventories:manageGroup' object.pk %}">{{ object.name }}</a></td>
                            <td>{{ object.date_modified|date:"Y-m-d H:i:s" }}</td>
                            <td>
                                <button id="deletebutton{{ object.pk }}" type="button"
                                        class="btn btn-default btn-xs"
                                        data-target=".bs-example-modal-sm" data-pk="{{ object.pk }}"
                                        data-name="{{ object.name }}"
                                        data-posttarget="/inventories/deletegroup/">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                </button>
                                <a href="{% url 'inventories:editGroup' object.pk %}" class="btn btn-default btn-xs">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% include 'projects/pagination.html' %}
    {% include 'projects/modalConfirm.html' %}
{% endblock jumbotron %}

inventories/templates/inventories/inventoriesIndex.html
{% extends "inventories/base.html" %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Inventories" 'inventories:index' %}
{% endblock breadcrumbs %}
{% block jumbotron %}
    {{ block.super }}
    <div id="group-index-data">
        <div class="col-md1 col-md-offset-11" align="right">
            <a href={% url 'inventories:createInventory' %} type="button" class="btn btn-info">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add
            </a>
        </div>
        <div>
            <div class="bs-example" data-example-id="hoverable-table">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Modified</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for object in object_list %}
                        <tr id="row{{ object.pk }}" class="collapse in">
                            <th scope="row">{{ page_obj.start_index|add:forloop.counter|add:"-1" }}</th>
                            <td><a href="{% url 'inventories:manageInventory' object.pk %}">{{ object.name }}</a></td>
                            <td>{{ object.date_modified|date:"Y-m-d H:i:s" }}</td>
                            <td>
                                <button id="deletebutton{{ object.pk }}" type="button"
                                        class="btn btn-default btn-xs"
                                        data-target=".bs-example-modal-sm" data-pk="{{ object.pk }}"
                                        data-name="{{ object.name }}"
                                        data-posttarget="/inventories/deleteinventory/">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                </button>
                                <a href="{% url 'inventories:editInventory' pk=object.pk %}" class="btn btn-default btn-xs">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                </a>
{#                                <a href="{% url 'jobtemplates:runJobTemplate' pk=object.pk %}" class="btn btn-default btn-xs">#}
{#                                    <span class="glyphicon glyphicon-send" aria-hidden="true"></span>#}
{#                                </a>#}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% include 'projects/pagination.html' %}
    {% include 'projects/modalConfirm.html' %}
{% endblock jumbotron %}

inventories/templates/inventories/manageInventory.html
{% extends 'inventories/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Inventories" 'inventories:index' %}
    {% breadcrumb object.name 'inventories:manageInventory' object.pk %}
{% endblock breadcrumbs %}
{% block jumbotron %}
    {{ block.super }}
    <div class="row">
        <div class="col col-md-1">
            <a href={% url 'inventories:createGroup' inv_id=object.pk %} type="button" class="btn btn-info">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> CreateGroup
            </a>
        </div>
        <div class="col col-md-1 pull-right">
            <a href={% url 'inventories:createHost' inv_id=object.pk %} type="button" class="btn btn-info">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> CreateHost
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col col-md-5">
            <div class="text-center">
                Hosts in inventory {{ object.name }}
            </div>
            <form id="{{ object.pk }}" method="post" action="{% url 'inventories:manageInventory' object.pk %}">
                {% csrf_token %}
                {{ form.hosts }}
                <div class="text-center">
                    Groups in inventory {{ object.name }}
                </div>
                {{ form.groups }}
                {% bootstrap_field form.name field_class='hidden' show_label=False %}
                {% bootstrap_field form.variables %}
                {% buttons %}
                    <button type="submit" id="saveMultiselect" class="btn btn-primary">
                        {% bootstrap_icon "ok" %} Save
                    </button>
                    <a href="{% url 'inventories:index' %}" type="button" class="btn btn-default">
                        {% bootstrap_icon "remove" %} Cancel
                    </a>
                {% endbuttons %}
            </form>
        </div>
        <div class="col col-md-2">
            <br/>
            <br/>
            <br/>
            <br/>
            <button type="button" id="HostSearch_leftSelected" class="btn btn-block"><i
                    class="glyphicon glyphicon-chevron-left"></i></button>
            <button type="button" id="HostSearch_rightSelected" class="btn btn-block"><i
                    class="glyphicon glyphicon-chevron-right"></i></button>
        </div>
        <div class="col col-md-5">
            <div class="text-center">
                Avalible hosts
            </div>
            <select name="to[]" id="HostSearch_to" class="form-control" size="8" multiple="multiple">
                {% for all_host in all_hosts %}
                    <option value="{{ all_host.pk }}">{{ all_host.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col col-md-2">
            <br/>
            <br/>
            <br/>
            <br/>
            <button type="button" id="GroupSearch_leftSelected" class="btn btn-block"><i
                    class="glyphicon glyphicon-chevron-left"></i></button>
            <button type="button" id="GroupSearch_rightSelected" class="btn btn-block"><i
                    class="glyphicon glyphicon-chevron-right"></i></button>
        </div>
        <div class="col col-md-5">
            <div class="text-center">
                Avalible groups
            </div>
            <select name="to[]" id="GroupSearch_to" class="form-control" size="8" multiple="multiple">
                {% for all_group in all_groups %}
                    <option value="{{ all_group.pk }}">{{ all_group.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    {% include 'inventories/codemirror.html' %}
{% endblock jumbotron %}
{% block jsload %}
    {{ block.super }}
    <script src="{% static 'js/multiselect.js' %}"></script>
    <script src="{% static 'js/multiselectPost.js' %}"></script>
{% endblock jsload %}